[tox]
env_list =
    py3
minversion = 4.21.2

[testenv]
description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    pytest>=6
    -r requirements.txt
skip_install = true  # To bypass the error "Multiple top-level packages discovered"
commands_pre =
    python manage.py test
    python manage.py migrate
commands =
    pip list
    {posargs:python manage.py runserver localhost:5000}

